matrix:
  include:
    - name: "Java 1.8 on Trusty Linux"
      os: linux
      language: java        # this works for Linux but is an error on Windows
      dist: trusty          # jdk 8 not available on the xenial linux distro
      java: oraclejdk8
    - name: "Java 1.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: java' is an error on Travis CI Windows
      before_install:
        # Tell Travis we want to use Powershell
        # https://docs.travis-ci.com/user/reference/windows/#powershell
        - powershell
        # Install java/maven
        - pwsh windows-install-java.sh
script:
  - cd snapshot-matcher
  - mvn install
  - cd ../snapshot-matcher-example
  - mvn install